# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
create_project -in_memory -part xc7k325tffg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir S:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.cache/wt [current_project]
set_property parent.project_path S:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.xci
set_property is_locked true [get_files s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top pcie_k7_gen2x4 -part xc7k325tffg676-2 -mode out_of_context
rename_ref -prefix_all pcie_k7_gen2x4_
write_checkpoint -noxdef pcie_k7_gen2x4.dcp
catch { report_utilization -file pcie_k7_gen2x4_utilization_synth.rpt -pb pcie_k7_gen2x4_utilization_synth.pb }
if { [catch {
  file copy -force S:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.runs/pcie_k7_gen2x4_synth_1/pcie_k7_gen2x4.dcp s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen2015/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
