# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.xci
# IP: The module: 'pcie_k7_gen2x4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/source/pcie_k7_gen2x4-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_gen2x4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/synth/pcie_k7_gen2x4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_gen2x4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.xci
# IP: The module: 'pcie_k7_gen2x4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/source/pcie_k7_gen2x4-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_gen2x4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/synth/pcie_k7_gen2x4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_gen2x4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
