# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7k325tffg676-2
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir S:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.cache/wt [current_project]
set_property parent.project_dir S:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen [current_project]
catch { write_hwdef -file pcie_k7_gen2x4.hwdef }
synth_design -top pcie_k7_gen2x4 -part xc7k325tffg676-2 -mode out_of_context

rename_ref -prefix_all pcie_k7_gen2x4_
write_checkpoint -noxdef pcie_k7_gen2x4.dcp
report_utilization -file pcie_k7_gen2x4_utilization_synth.rpt -pb pcie_k7_gen2x4_utilization_synth.pb
if { [catch {
  file copy -force S:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.runs/pcie_k7_gen2x4_synth_1/pcie_k7_gen2x4.dcp s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4.dcp
  write_verilog -force -mode synth_stub s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_stub.v
  write_vhdl -force -mode synth_stub s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_stub.vhdl
  write_verilog -force -mode funcsim s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_funcsim.v
  write_vhdl -force -mode funcsim s:/workspace/CXK7T360/XC7K325T-2/PCIe_DMA/ipcore_gen/gvi_k7x4gen2.srcs/sources_1/ip/pcie_k7_gen2x4/pcie_k7_gen2x4_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
